language: node_js
node_js:
  - "4.5.0"
before_script:
  - npm install -g angular-cli@1.1.3
before_install:
  - if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
