configmap:
  cdx:
    name: cdx-card-service-update
    eventhub:
      namespace: s00199-enscdx-sd-us-card-na1
      shared_access:
        keyname: enscdx-card-SASsendlisten
        password_kvkey: cdxevh-sd-us-access-key-card-na1
      ingestion_path_update: evhcdx-card-update
      path_dlq: evhcdx-card-dlq
    azure:
      tenant_id: ee69be27-d938-4eb5-8711-c5e69ca43718
      keyvault:
        host: s00199nkvt10001.vault.azure.net
        url: https://s00199nkvt10001.vault.azure.net
      encryptaes_secret_kvkey: cdxapi-sd-us-encryptaes-secret
      encryptiv_salt_kvkey: cdxapi-sd-us-encryptiv-salt
      payload:
        encryptaes_secret_kvkey: cdxapi-sd-us-encrypt-payload-aes-secret
        encryptiv_salt_kvkey: cdxapi-sd-us-encrypt-payload-iv-salt
    java_options: 
    app_log_level: trace
    app_stdout_color: false

deployment:
  spec:
    replicas: 1
    minreadyseconds: 35
    strategy:
      type: RollingUpdate
      maxunavailable: 1
      maxsurge: 2
  app: cdx-card-service-update
  container:
    image: image
    resources:
      memory:
        limits: 1Gi
        requests: 1Gi
      cpu:
        limits: "1"
        requests: "0.1"
    port:
      cdx: 7013
      healthz: 7030
    livenessprobe:
      httpget:
        path: /health
        port: healthz
      initialdelayseconds: 60
      periodseconds: 30
      timeoutseconds: 10
    readinessprobe:
      httpget:
        path: /health
        port: healthz
      initialdelayseconds: 60
      periodseconds: 30
      timeoutseconds: 10
#Enable 'envform:' variables (from line 69-86) if it's "service-registration or service-update" microservices
#  envform:
#    name: 
#  envs:
#    env1:
#      name: 
#      fieldref:
#        apiversion: v1
#        fieldpath: spec.nodeName
#    env2:
#      name: 
#      secretkeyref:
#        name: 
#        key: 
#    env3:
#      name: 
#      secretkeyref:
#        name: 
#        key: 
  imagepullsecrets:
    name: 

autoscale:
  spec:
    minreplicas: 1
    maxreplicas: 1
    targetcpuutil: 50